# Setup
title:            "10c8@blog"
tagline:          "Tales of code and insomnia."
description:      "Tales of code and insomnia."
url:              http://10c8.github.io

# Social
author:
    name:         "10c8"
    url:          https://github.com/10c8

social:
    name:         "William Fernandes"
    links:
        - https://10c8.github.com/
        - https://github.com/10c8/
        - https://twitter.com/10c8_

# Markdown and syntax-highlighting
markdown:         kramdown
highlighter:      rouge

kramdown:
    input:              GFM
    syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Atom feed
feed:
    path:         feed.xml

# Paginator
paginate:         3

# Gems
gems:
    - jekyll-feed
    - jemoji
#   - algoliasearch-jekyll

# Exclusions
exclude:
    - scripts
    - LICENSE.md
    - README.md
    - Gemfile
    - Gemfile.lock
    - CNAME

# Minifier
# jekyll-minifier:
#     exclude: ["feed.xml", "sitemap.xml"]

compress_html:
    clippings: all
    comments: all
    endings: all
    blanklines: true
    startings: [html, head, body]

# Algolia search
# algolia:
#     application_id: '6N8GERIOH7'
#     index_name:     '10c8-blog'
