# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
    input:              GFM
    syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            "10c8@blog"
tagline:          "Tales of code and insomnia."
description:      "..."
url:              http://10c8.github.io

author:
    name:         '10c8'
    url:          https://github.com/10c8

paginate:         5
