# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
    input:              GFM
    syntax_highlighter: rouge

gems: ["jemoji"]

# Permalinks
permalink:        pretty

# Setup
title:            "10c8@blog"
tagline:          "Tales of code and insomnia."
description:      "..."
url:              http://10c8.github.io

author:
    name:         "10c8"
    url:          https://github.com/10c8

social:
    name:         "William Fernandes"
    links:
        - https://10c8.github.com/
        - https://github.com/10c8

feed:
    path:         atom.xml

paginate:         5

jekyll-minifier:
    exclude:
        - "atom.xml"
        - "LICENSE.md"
        - "README.md"
