# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
    input:              GFM
    syntax_highlighter: rouge

gems:
    - jekyll-feed
    - jemoji

# Permalinks
permalink:        pretty

# Setup
title:            "10c8@blog"
tagline:          "Tales of code and insomnia."
description:      "Tales of code and insomnia."
url:              http://10c8.github.io

author:
    name:         "10c8"
    url:          https://github.com/10c8

social:
    name:         "William Fernandes"
    links:
        - https://10c8.github.com/
        - https://github.com/10c8/
        - https://twitter.com/10c8_

feed:
    path:         feed.xml

paginate:         3

jekyll-minifier:
    exclude:
        - atom.xml
        - sitemap.xml
        - LICENSE.md
        - README.md
